### ISSUE TITLE
TWatch-2020-V1 won't boot after firmware update

### ISSUE THREAD

**Issue by miggat** [JohnySeven/TWatchSKDesigner#15]
Tried 0.9 alpha in both Windows 10 and Ubuntu 20.04.

When I run Firmware > Update (Clear device flash), the watch won't boot any more.

Tried with no views at all and with 1 basic view, with same results:

- Erasing flash ...
- Serial port /dev/ttyACM0
- Detecting type...
- Connecting

After that, nothing, the watch won't boot.

**Comment by miggat** [comment]
Ok, so I followed this steps (both linux and windows):
1) Run TWatch SK Designer as sudo/admin
2) Click on Firmware > Update
3) Select the proper port (there's only 1, so i assume it's ok)
4) Checked "Clear device flash prior upload"
5) Click "Upload" button
6) Wait for the process to finish
7) Wait up to 5 minutes while looking at the watch screen

Results:
· Nothing is displayed on the watch during the entire process
· Nothing seems to happen after 5 minutes
· Quick press the watch button does nothing
· Long press the watch button does nothing
· Double tap watch screen does nothing

To make sure the issue wasn't on the device itself, I tried uploading another image (not SK related) with platformio without issues, so I guess Watch, cable, and usb port is fine.

Let me know if I understood correctly what you asked me to test and if there is any further info I can provide.

**Comment by miggat** [comment]
So, I cloned the repo and test with the latest commit, in debug mode, and this is the output, in case it helps:

> PROGRESS: Checking if esptool is downloaded...
> PROGRESS: esptool exists at C:\Users\user\AppData\Local\TWatchDesigner\Esptool\esptool.exe...
> PROGRESS: Downloading firmware from https://dev.dytrych.cloud/twatchsk.zip
> PROGRESS: Extracting firmware archive...
> PROGRESS: Erasing flash...
> PROGRESS: esptool.py v3.2
> PROGRESS: Serial port COM6
> PROGRESS: Connecting....
> PROGRESS: Chip is ESP32-D0WDQ6-V3 (revision 3)
> PROGRESS: Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
> PROGRESS: Crystal is 40MHz
> PROGRESS: MAC: 08:3a:f2:66:3d:50
> PROGRESS: Uploading stub...
> PROGRESS: Running stub...
> PROGRESS: Stub running...
> PROGRESS: Erasing flash (this may take a while)...
> PROGRESS: Chip erase completed successfully in 29.3s
> PROGRESS: Hard resetting via RTS pin...
> PROGRESS: 
> PROGRESS: Uploading new Firmware version 0.9...
> PROGRESS: esptool.py v3.2
> PROGRESS: Serial port COM6
> PROGRESS: Connecting....
> PROGRESS: Detecting chip type... Unsupported detection protocol, switching and trying again...
> PROGRESS: Connecting....
> PROGRESS: Detecting chip type... ESP32
> PROGRESS: Chip is ESP32-D0WDQ6-V3 (revision 3)
> PROGRESS: Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
> PROGRESS: Crystal is 40MHz
> PROGRESS: MAC: 08:3a:f2:66:3d:50
> PROGRESS: Uploading stub...
> PROGRESS: Running stub...
> PROGRESS: Stub running...
> PROGRESS: Changing baud rate to 800000
> PROGRESS: Changed.
> PROGRESS: Configuring flash size...
> PROGRESS: 
> 

I waited for ~10 minutes, but it stayed there

**Comment by miggat** [comment]
When I start the project, the file C:\Users\user\AppData\Local\TWatchDesigner\Firmware\firmware.json is created with the arguments:

> "arguments" : "--baud 800000 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 40m --flash_size detect"

The baud rate won't work, but if I modify it it to 112500 before flashing, everything runs as expected.

**Comment by JohnySeven** [comment]
Sorry, I was little confused, from your description, I thought the issue was after firmware upload is completed.

I'm glad you've figured it out. Baudrate 800000 works fine for our 3 development watches, but I could change json file to lower the baud rate, no issue here.

Could you please test 400000 bauds for upload if it works for you?

Maybe there is some HW revision that is using different USB to UART chip that doesn't handle high speed transfer.

Please let me know!

Thanks

**Comment by miggat** [comment]
Tested with 400000, and it works fine too

**Comment by JohnySeven** [comment]
OK, I've changed to 400000 bauds!

Thanks for testing TWatchSK!
